service: auth-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ${env:region, 'us-east-1'}
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: ${env:AWS_NODEJS_CONNECTION_REUSE_ENABLED,'1'}
  iamRoleStatements:
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: "*"

functions:
  basicAuthorizer:
    handler: src/functions/index.basicAuthorizer

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: aws-sdk
    target: node14
    platform: node
    concurrency: 10
  serverless-offline:
    allowCache: true
    noTimeOut: true
    httpPort: 5000
    lambdaPort: 5002
  useDotEnv: true

package:
  individually: true
